// Auto-generated mapping article/famille → image file in assets/pieces/
// Regenerate via: python3 scripts/build-image-manifest.py
window.PIECE_IMAGES = {
  "articles": {
    "Bv2Biaise": "Bv2Biaise.PNG",
    "Bv2Plis": "Bv2Plis.PNG",
    "Bv2Plis-90deg": "Bv2Plis-90deg.PNG",
    "Bv3Plis": "Bv3Plis.PNG",
    "Bv3Plis-90deg": "Bv3Plis-90deg.PNG",
    "Bv3PlisBiaise": "Bv3PlisBiaise.PNG",
    "Bv4Plis": "Bv4Plis.PNG",
    "Bv4Plis-90deg": "Bv4Plis-90deg.PNG",
    "Bv4PlisBiaise": "Bv4PlisBiaise.PNG",
    "Bv4PlisPerfos": "Bv4PlisPerfos.PNG",
    "Bavette 2 Plis Encoche Droite Generique": "Capture Bavette 2 Plis Encoche Droite Generique.PNG",
    "Bavette 2 Plis Encoche Gauche Generique": "Capture Bavette 2 Plis Encoche Gauche Generique.PNG",
    "Bavette 2 Plis Encoche Generique": "Capture Bavette 2 Plis Encoche Generique.PNG",
    "Bavette 2 Plis Generique": "Capture Bavette 2 Plis Generique.PNG",
    "Bavette 2 Plis Rayonne": "Capture Bavette 2 Plis Rayonne.PNG",
    "Bavette 3 Plis Encoche Droite Generique": "Capture Bavette 3 Plis Encoche Droite Generique.PNG",
    "Bavette 3 Plis Encoche Gauche Generique": "Capture Bavette 3 Plis Encoche Gauche Generique.PNG",
    "Bavette 3 Plis Encoche Generique": "Capture Bavette 3 Plis Encoche Generique.PNG",
    "Bavette 3 Plis Encoche": "Capture Bavette 3 Plis Encoche.PNG",
    "Bavette 3 Plis Encoches et Relevées": "Capture Bavette 3 Plis Encoches et Relevées .PNG",
    "Bavette 3 Plis Generique": "Capture Bavette 3 Plis Generique.PNG",
    "Bavette 3 Plis Rayonne": "Capture Bavette 3 Plis Rayonne.PNG",
    "Bavette 3 Plis Releve Droite": "Capture Bavette 3 Plis Releve Droite.PNG",
    "Bavette 3 Plis Releve Gauche": "Capture Bavette 3 Plis Releve Gauche.PNG",
    "Bavette 3 Plis Releves": "Capture Bavette 3 Plis Releves.PNG",
    "Bavette 4 Plis Encoche Droite Generique": "Capture Bavette 4 Plis Encoche Droite Generique.PNG",
    "Bavette 4 Plis Encoche Gauche Generique": "Capture Bavette 4 Plis Encoche Gauche Generique.PNG",
    "Bavette 4 Plis Encoche Generique": "Capture Bavette 4 Plis Encoche Generique.PNG",
    "Bavette 4 Plis Generique": "Capture Bavette 4 Plis Generique.PNG",
    "Bavette 4 Plis Rayonne": "Capture Bavette 4 Plis Rayonne.PNG",
    "Bavette Pente 2 Plis Rabat à droite": "Capture Bavette Pente 2 Plis Rabat à droite.PNG",
    "Bavette Pente 2 Plis Rabat à Gauche": "Capture Bavette Pente 2 Plis Rabat à Gauche.PNG",
    "Bavette Pente 2 Plis Rabat+Ge à droite": "Capture Bavette Pente 2 Plis Rabat+Ge à droite.PNG",
    "Bavette Pente 2 Plis Rabat+Ge à gauche": "Capture Bavette Pente 2 Plis Rabat+Ge à gauche.PNG",
    "Bavette Pente 2 Plis Rabats+Ge": "Capture Bavette Pente 2 Plis Rabats+Ge.PNG",
    "Bavette Pente 3 Plis Rabat à droite": "Capture Bavette Pente 3 Plis Rabat à droite.PNG",
    "Bavette Pente 3 Plis Rabat à Gauche": "Capture Bavette Pente 3 Plis Rabat à Gauche.PNG",
    "Bavette Pente 3 Plis Rabat+Ge à droite": "Capture Bavette Pente 3 Plis Rabat+Ge à droite.PNG",
    "Bavette Pente 3 Plis Rabat+Ge à gauche": "Capture Bavette Pente 3 Plis Rabat+Ge à gauche.PNG",
    "Bavette Pente 3 Plis Rabats+Ge": "Capture Bavette Pente 3 Plis Rabats+Ge.PNG",
    "Bavette Pente 4 Plis Rabat à droite": "Capture Bavette Pente 4 Plis Rabat à droite.PNG",
    "Bavette Pente 4 Plis Rabat à Gauche": "Capture Bavette Pente 4 Plis Rabat à Gauche.PNG",
    "Bavette Pente 4 Plis Rabat+Ge à droite": "Capture Bavette Pente 4 Plis Rabat+Ge à droite.PNG",
    "Bavette Pente 4 Plis Rabat+Ge à gauche": "Capture Bavette Pente 4 Plis Rabat+Ge à gauche.PNG",
    "Bavette Pente 4 Plis Rabats+Ge": "Capture Bavette Pente 4 Plis Rabats+Ge.PNG",
    "Bavette Plate 2 Plis Rabat à droite": "Capture Bavette Plate 2 Plis Rabat à droite.PNG",
    "Bavette Plate 2 Plis Rabat à Gauche": "Capture Bavette Plate 2 Plis Rabat à Gauche.PNG",
    "Bavette Plate 2 Plis RabatGe à droite": "Capture Bavette Plate 2 Plis RabatGe à droite.PNG",
    "Bavette Plate 2 Plis RabatGe à gauche": "Capture Bavette Plate 2 Plis RabatGe à gauche.PNG",
    "Bavette Plate 3 Plis Rabat à droite": "Capture Bavette Plate 3 Plis Rabat à droite.PNG",
    "Bavette Plate 3 Plis Rabat à Gauche": "Capture Bavette Plate 3 Plis Rabat à Gauche.PNG",
    "Bavette Plate 3 Plis RabatGe à droite": "Capture Bavette Plate 3 Plis RabatGe à droite.PNG",
    "Bavette Plate 3 Plis RabatGe à gauche": "Capture Bavette Plate 3 Plis RabatGe à gauche.PNG",
    "Bavette Plate 4 Plis Rabat à droite": "Capture Bavette Plate 4 Plis Rabat à droite.PNG",
    "Bavette Plate 4 Plis Rabat à Gauche": "Capture Bavette Plate 4 Plis Rabat à Gauche.PNG",
    "Bavette Plate 4 Plis RabatGe à droite": "Capture Bavette Plate 4 Plis RabatGe à droite.PNG",
    "Bavette Plate 4 Plis RabatGe à gauche": "Capture Bavette Plate 4 Plis RabatGe à gauche.PNG",
    "Bavettes Generique": "Capture Bavettes Generique.PNG",
    "Bv 4 Plis Plate": "Capture Bv 4 Plis Plate.PNG",
    "Bv Pente 2 Plis Ge Ecrasée": "Capture Bv Pente 2 Plis Ge Ecrasée.PNG",
    "Bv Pente 3 Plis Ge Ecrasée": "Capture Bv Pente 3 Plis Ge Ecrasée.PNG",
    "Bv Pente 4 Plis Ge Ecrasée": "Capture Bv Pente 4 Plis Ge Ecrasée.PNG",
    "Bv Plate 2 Plis Ge Ecrasée": "Capture Bv Plate 2 Plis Ge Ecrasée.PNG",
    "Bv Plate 3 Plis Ge Ecrasée": "Capture Bv Plate 3 Plis Ge Ecrasée.PNG",
    "Bv Plate 4 Plis Ge Ecrasée": "Capture Bv Plate 4 Plis Ge Ecrasée.PNG",
    "AnglePenteRentrantBv2": "Capture AnglePenteRentrantBv2.PNG",
    "AnglePenteRentrantBv3": "Capture AnglePenteRentrantBv3.PNG",
    "AnglePenteRentrantBv4": "Capture AnglePenteRentrantBv4.PNG",
    "AnglePenteSortantBv2": "Capture AnglePenteSortantBv2.PNG",
    "AnglePenteSortantBv3": "Capture AnglePenteSortantBv3.PNG",
    "AnglePenteSortantBv4": "Capture AnglePenteSortantBv4.PNG",
    "AnglePlatRentrantBv2": "Capture AnglePlatRentrantBv2.PNG",
    "AnglePlatRentrantBv3": "Capture AnglePlatRentrantBv3.PNG",
    "AnglePlatRentrantBv4": "Capture AnglePlatRentrantBv4.PNG",
    "AnglePlatSortantBv2": "Capture AnglePlatSortantBv2.PNG",
    "AnglePlatSortantBv3": "Capture AnglePlatSortantBv3.PNG",
    "AnglePlatSortantBv4": "Capture AnglePlatSortantBv4.PNG",
    "BouchBvPente-D": "Capture BouchBvPente-D.PNG",
    "BouchBvPente-G": "Capture BouchBvPente-G.PNG",
    "BouchBvPlate-D": "Capture BouchBvPlate-D.PNG",
    "BouchBvPlate-G": "Capture BouchBvPlate-G.PNG",
    "EqAC Ext A Coller": "Capture EqAC Ext A Coller.PNG",
    "EqAC Int A Coller": "Capture EqAC Int A Coller.PNG",
    "Equerre de Finition Laquage Ext": "Capture Equerre de Finition Laquage Ext.PNG",
    "Equerre de Finition Laquage Int": "Capture Equerre de Finition Laquage Int.PNG",
    "Releve 1 Pli Droite": "Capture Releve 1 Pli Droite.PNG",
    "Releve 1 Pli Gauche": "Capture Releve 1 Pli Gauche.PNG",
    "Releve 1 Pli": "Capture Releve 1 Pli.PNG",
    "Releve 2 Plis Droite": "Capture Releve 2 Plis Droite.PNG",
    "Releve 2 Plis Gauche": "Capture Releve 2 Plis Gauche.PNG",
    "Releve 2 Plis": "Capture Releve 2 Plis.PNG",
    "Releve Type1 Bavette Rayonnée Droite": "Capture Releve Type1 Bavette Rayonnée Droite.PNG",
    "Releve Type1 Bavette Rayonnée Gauche": "Capture Releve Type1 Bavette Rayonnée Gauche.PNG",
    "Releve Type2 Bavette Rayonnée Droite": "Capture Releve Type2 Bavette Rayonnée Droite.PNG",
    "Releve Type2 Bavette Rayonnée Gauche": "Capture Releve Type2 Bavette Rayonnée Gauche.PNG",
    "Support Bavette Pentée 1 Pli": "Capture Support Bavette Pentée 1 Pli.PNG",
    "Support Bavette Pentée 2 Plis": "Capture Support Bavette Pentée 2 Plis.PNG",
    "Support Bavette Plate 1 Pli": "Capture Support Bavette Plate 1 Pli.PNG",
    "Support Bavette Plate 2 Plis": "Capture Support Bavette Plate 2 Plis.PNG",
    "EclExtBv2": "EclExtBv2.PNG",
    "EclExtBv2Ray": "EclExtBv2Ray.PNG",
    "EclExtBv3": "EclExtBv3.PNG",
    "EclExtBv3Plate": "EclExtBv3Plate.PNG",
    "EclExtBv3Ray": "EclExtBv3Ray.PNG",
    "EclExtBv4": "EclExtBv4.PNG",
    "EclExtBv4Plate": "EclExtBv4Plate.PNG",
    "EclExtBv4Ray": "EclExtBv4Ray.PNG",
    "EclIntBv2": "EclIntBv2.PNG",
    "EclIntBv3et4": "EclIntBv3et4.PNG",
    "Couvertine Pente Clipse": "Capture Couvertine Pente Clipse.PNG",
    "Couvertine Pente Collee": "Capture Couvertine Pente Collee.PNG",
    "Couvertine Pente Ge Ecrasé": "Capture Couvertine Pente Ge Ecrasé.PNG",
    "Couvertine Plate 1 Rabat Ge": "Capture Couvertine Plate 1 Rabat Ge.PNG",
    "Couvertine Plate 1 Rabat": "Capture Couvertine Plate 1 Rabat.PNG",
    "Couvertine Plate 2 Rabats Ge": "Capture Couvertine Plate 2 Rabats Ge.PNG",
    "Couvertine Plate 2 Rabats": "Capture Couvertine Plate 2 Rabats.PNG",
    "Couvertine Plate Clipse": "Capture Couvertine Plate Clipse.PNG",
    "Couvertine Plate Collee Ge Ecrasé": "Capture Couvertine Plate Collee Ge Ecrasé.PNG",
    "Couvertine Plate Collee": "Capture Couvertine Plate Collee.PNG",
    "Couvertine Plate Descendante": "Capture Couvertine Plate Descendante.PNG",
    "Couvertine Plate Montante": "Capture Couvertine Plate Montante.PNG",
    "Couvertines": "Capture Couvertines generique.PNG",
    "Angle Couvertine Plate Collee Ouverture Variable": "Capture Angle Couvertine Plate Collee Ouverture Variable.PNG",
    "Angle Couvertine Plate Collee": "Capture Angle Couvertine Plate Collee.PNG",
    "Angle Rentrant Couvertine Clipse Ouverture Variable": "Capture Angle Rentrant Couvertine Clipse Ouverture Variable.PNG",
    "Angle Rentrant Couvertine Clipse": "Capture Angle Rentrant Couvertine Clipse.PNG",
    "Angle Rentrant Couvertine Collee": "Capture Angle Rentrant Couvertine Collee.PNG",
    "Angle Rentrant Couvertine Plate Clipse": "Capture Angle Rentrant Couvertine Plate Clipse.PNG",
    "Angle Sortant Couvertine Clipse Ouverture Variable": "Capture Angle Sortant Couvertine Clipse Ouverture Variable.PNG",
    "Angle Sortant Couvertine Clipse": "Capture Angle Sortant Couvertine Clipse.PNG",
    "Angle Sortant Couvertine Collee": "Capture Angle Sortant Couvertine Collee.PNG",
    "Angle Sortant Couvertine Plate Clipse Ouverture Variable": "Capture Angle Sortant Couvertine Plate Clipse Ouverture Variable.PNG",
    "Angle Sortant Couvertine Plate Clipse": "Capture Angle Sortant Couvertine Plate Clipse.PNG",
    "Angle Sortant Couvertine Plate": "Capture Angle Sortant Couvertine Plate.PNG",
    "Angle T couvertine Pente Clipse": "Capture Angle T couvertine Pente Clipse.PNG",
    "Angle T couvertine Pente Collee": "Capture Angle T couvertine Pente Collee.PNG",
    "Angle T Couvertine Plate Clipse": "Capture Angle T Couvertine Plate Clipse.PNG",
    "Angle T Couvertine Plate Collee": "Capture Angle T Couvertine Plate Collee.PNG",
    "BouchCouvPente-D": "Capture BouchCouvPente-D.PNG",
    "BouchCouvPente-D-Ge": "Capture BouchCouvPente-D-Ge.PNG",
    "BouchCouvPente-G": "Capture BouchCouvPente-G.PNG",
    "BouchCouvPente-G-Ge": "Capture BouchCouvPente-G-Ge.PNG",
    "Bouchon Couvertine Plate Ge": "Capture Bouchon Couvertine Plate Ge.PNG",
    "Bouchon Couvertine Plate": "Capture Bouchon Couvertine Plate.PNG",
    "EclExt Couvertine Pente Clipse": "Capture EclExt Couvertine Pente Clipse.PNG",
    "EclExt Couvertine Pente Collee": "Capture EclExt Couvertine Pente Collee.PNG",
    "EclExt Couvertine Plate Clipse": "Capture EclExt Couvertine Plate Clipse.PNG",
    "EclExt Couvertine Plate Collee": "Capture EclExt Couvertine Plate Collee.PNG",
    "EclInt Couvertine Pente Clipse": "Capture EclInt Couvertine Pente Clipse.PNG",
    "EclInt Couvertine Pente Collee": "Capture EclInt Couvertine Pente Collee.PNG",
    "EclInt Couvertine Plate Clipse": "Capture EclInt Couvertine Plate Clipse.PNG",
    "EclInt Couvertine Plate Collee": "Capture EclInt Couvertine Plate Collee.PNG",
    "Releve Couvertine": "Capture Releve Couvertine.PNG",
    "Rustine à Coller": "Capture Rustine à Coller.PNG",
    "Support Nervure Couvertine Création de Pente": "Capture Support Nervure Couvertine Création de Pente.PNG",
    "Support Nervure Couvertine pente": "Capture Support Nervure Couvertine pente.PNG",
    "Support Nervure Couvertine penteRetombVerticales": "Capture Support Nervure Couvertine penteRetombVerticales.PNG",
    "Support Nervure Couvertine plate": "Capture Support Nervure Couvertine plate.PNG",
    "Support Nervure Couvertine plateRetombVerticales": "Capture Support Nervure Couvertine plateRetombVerticales.PNG",
    "BouchPente-D": "Capture BouchPente-D.PNG",
    "BouchPlat-D": "Capture BouchPlat-D.PNG",
    "BouchPlat-G": "Capture BouchPlat-G.PNG",
    "Couvre joint Angle Ext Perfos": "Capture Couvre joint Angle Ext Perfos.PNG",
    "Couvre joint Angle Ext": "Capture Couvre joint Angle Ext.PNG",
    "Couvre joint Angle Int Perfos": "Capture Couvre joint Angle Int Perfos.PNG",
    "Couvre joint Angle Int": "Capture Couvre joint Angle Int.PNG",
    "Couvre joint Angle Z": "Capture Couvre joint Angle Z.PNG",
    "Couvre joint Angle Z-Perfos": "Capture Couvre joint Angle Z-Perfos.PNG",
    "Couvre joint Angle Z-PerfosHaute": "Capture Couvre joint Angle Z-PerfosHaute.PNG",
    "Couvre Joint Plat Perfos": "Capture Couvre Joint Plat Perfos.PNG",
    "Couvre joint Plat": "Capture Couvre joint Plat.PNG",
    "Omega Laque Ext": "Capture Omega Laque Ext.PNG",
    "Omega Laque Int": "Capture Omega Laque Int.PNG",
    "Omega": "Capture Omega.PNG",
    "Couvre Joint General": "Couvre Joint General.PNG",
    "Depart Type 1": "Capture Depart Type 1.PNG",
    "Depart Type OSP": "Capture Depart Type OSP.PNG",
    "Depart": "Capture Depart.PNG",
    "Angle": "Capture AnglePlatSortantBv4.PNG",
    "Divers": "Profil Divers.PNG",
    "Omega Brut": "Capture Omega.PNG",
    "Plat": "Capture BouchPlat-D.PNG",
    "Lateraux": "Capture Lateraux.PNG",
    "Goussets Lisse Type 3": "Capture Goussets Lisse Type 3.PNG",
    "Lisse Poralu": "Capture Lisse Poralu.PNG",
    "Lisse PoraluType2": "Capture Lisse PoraluType2.PNG",
    "Lisse Type 1": "Capture Lisse Type 1.PNG",
    "Lisse Type 2": "Capture Lisse Type 2.PNG",
    "Lisse Type 3": "Capture Lisse Type 3.PNG",
    "Lisse Type 3-Goussets": "Capture Lisse Type 3-Goussets.PNG",
    "Lisse Type 4": "Capture Lisse Type 4.PNG",
    "Profil Divers": "Profil Divers.PNG",
    "Profil-1": "Profil-1.PNG",
    "Profil-1-Perfos Type 1": "Profil-1-Perfos Type  1.PNG",
    "Profil-1-Perfos Type 2": "Profil-1-Perfos Type  2.PNG",
    "Ge Type 1": "Capture Ge Type 1.PNG",
    "Solins et Ge Pliées": "Capture Solins et Ge Pliées.PNG",
    "Ge Type 1 Non Perfores": "Ge Type 1 Non Perfores.PNG",
    "Accessoires Solins et Ge Pliées": "Capture Accessoires Solins et Ge Pliées.PNG",
    "EclInt Ge Type 1": "Capture EclInt Ge Type 1.PNG"
  },
  "familles": {
    "Bavette": "Bv2Biaise.PNG",
    "Bavette Accessoire": "Capture AnglePenteRentrantBv2.PNG",
    "Couvertine": "Capture Couvertine Pente Clipse.PNG",
    "Couvertine Accessoire": "Capture Angle Couvertine Plate Collee Ouverture Variable.PNG",
    "Couvre Joint": "Capture BouchPente-D.PNG",
    "Departs": "Capture Depart Type 1.PNG",
    "Divers": "Capture AnglePlatSortantBv4.PNG",
    "Lateraux": "Capture Lateraux.PNG",
    "Lisses": "Capture Goussets Lisse Type 3.PNG",
    "Profils Divers": "Profil Divers.PNG",
    "Solin et Ge Pliées": "Capture Ge Type 1.PNG",
    "Solins et Ge Pliées Accessoires": "Capture Accessoires Solins et Ge Pliées.PNG"
  }
};
